title: <p align="center"> Alya Puspita Zahra </p>

logo: "https://postimg.cc/c697QJ18"

description:
  <p align="center">
  <a href="https://www.instagram.com/alyapspt_/">Instagram</a> |
  <a href="https://www.linkedin.com/in/alya-puspita-zahra-75a624205/">LinkedIn</a> |
  
  <p align="justify">
  I am an undergraduate student majoring in Physics Education at Mulawarman University.
  <br><br>
  I am an enthusiastic learner and have interests in education such as being a teacher and researcher according to my educational background.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
